### ISSUE TITLE
Bugs: AccessDeniedException: Resource is not in the state functionActive

### ISSUE THREAD

**Issue by go-to-k** [go-to-k/image-scanner-with-dockle#5]
Version: v1.0.9

When I deployed, I got the following error in CloudFormation Event message.

(This deployment has no changes in Lambda, IAM Role and IAM Policy, only Custom Resource has changes for update.)

```
ECSConstruct/EcrConstruct/ImageScannerWithDockle/Default/Default (ECSConstructEcrConstructImageScannerWithDockle0DCA0262) Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: xxxxxxxxxxxxxxxxx)
```

**Comment by go-to-k** [comment]
Custom Resource Provider Role Policy missing?

https://stackoverflow.com/questions/76819690/accessdeniedexception-resource-is-not-in-the-state-functionactivev2-at-object-e

**Comment by go-to-k** [comment]
However, when I retried, I succeeded...

**Comment by go-to-k** [comment]
I'll close it this time for now.

**Comment by go-to-k** [comment]
Tried it multiple times with different stacks, but they say it will be the first.

And in all, retries are successful.

**Comment by go-to-k** [comment]
Provider has next policies.

AWSLambdaBasicExecutionRole

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "lambda:InvokeFunction",
            "Resource": [
                "arn:aws:lambda:ap-northeast-1:123456789012:function:dev-main-BastionTunnel-CustomImageScannerWithDockl-hzy008aOF787",
                "arn:aws:lambda:ap-northeast-1:123456789012:function:dev-main-BastionTunnel-CustomImageScannerWithDockl-hzy008aOF787:*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by go-to-k** [comment]
Retry succeeds, so I'll close it this time for now...

**Comment by Yatingambhir85** [comment]
What policy you have added to your role?  I am also getting the same AccessDenied error.

**Comment by go-to-k** [comment]
Users of this library do not need to specify explicit policies.
Apparently this is a bug on the aws-cdk side.

https://github.com/aws/aws-cdk/issues/26838

**Comment by go-to-k** [comment]
Seems to have been fixed yesterday. After this is released I will update the version of the dependent cdk for this tool.

https://github.com/aws/aws-cdk/pull/32904

**Comment by go-to-k** [comment]
The [new PR](https://github.com/aws/aws-cdk/pull/33315) has been merged instead of the [previous PR](https://github.com/aws/aws-cdk/pull/32904).

It is included in [v2.178.1](https://github.com/aws/aws-cdk/releases/tag/v2.178.1), so we will release our library with major version to upgrade a dep cdk version to the new version.
